import { chromium, type Browser } from "playwright";

// Arabic (and mixed Arabic/French) text needs real shaping and bidi layout
// that a PDF library like pdfkit does not do on its own — a real browser
// engine gets this right for free, so PDFs are generated by rendering an
// HTML letterhead and printing it, not by hand-positioning text.
let browserPromise: Promise<Browser> | null = null;

function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    // In production, run `npx playwright install chromium` at deploy time
    // and leave PLAYWRIGHT_CHROMIUM_PATH unset — Playwright finds its own
    // bundled browser. This override exists only for sandboxes/hosts with a
    // browser already installed somewhere Playwright wouldn't guess.
    const executablePath = process.env.PLAYWRIGHT_CHROMIUM_PATH || undefined;
    browserPromise = chromium.launch({ headless: true, executablePath }).catch((err) => {
      browserPromise = null;
      throw err;
    });
  }
  return browserPromise;
}

export async function renderHtmlToPdf(html: string): Promise<Buffer> {
  const browser = await getBrowser();
  const page = await browser.newPage();
  try {
    await page.setContent(html, { waitUntil: "networkidle" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "0", bottom: "0", left: "0", right: "0" },
    });
    return pdf;
  } finally {
    await page.close();
  }
}
